### ISSUE TITLE
Port forwarding doesn't work

### ISSUE THREAD

**Issue by tuomastielinen** [jordanpotter/transmission-nat-pmp#1]
I'm using transmission with macvlan networking to route it to Proton VPN via my router.

Here are the relevant parts from my docker compose:
```
 transmission:
    image: linuxserver/transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
    volumes:
      - ${CONFIGDIR}/transmission:/config
      - ${DATADIR}:/data
    ports:
      - 9091:9091
      - 54853:54853
      - 54853:54853/udp
    restart: unless-stopped
    mac_address: "02:42:c0:a8:01:d7"
    networks:
      macvlan-net:
        ipv4_address: 10.0.0.33
```

Docker's log shows:
```
2023-07-28T19:21:25.772646596Z [mod-init] Adding "jordanpotter/docker-mods:transmission-nat-pmp" to container
2023-07-28T19:21:27.109007102Z [mod-init] "jordanpotter/docker-mods:transmission-nat-pmp" could not be found on registry-1.docker.io
```

So I'm not sure if the mod is loaded correctly.

![image](https://github.com/jordanpotter/transmission-nat-pmp/assets/4067688/79dda27e-1bf0-4c38-a1d4-7a9d19989c07)
The port is showing as closed. I also tried checking "Use port forwarding from my router", with the same result.
